linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - gci
    - goconst
    - gosec
    - makezero
    - misspell
    - noctx
    - revive
    - sqlclosecheck
    - tagliatelle
    - unconvert
    - unparam
    - wastedassign
